branch-defaults:
  master:
    environment: secp-env
environment-defaults:
  secp-env:
    branch: null
    repository: null
global:
  application_name: SECP
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Java 8 running on
    64bit Amazon Linux/2.6.0
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
